### ISSUE TITLE
IE11 / EDGE not supported

### ISSUE THREAD

**Issue by alansaldivar87** [gruhn/vue-qrcode-reader#10]
Nothing to say related to explorer but yes regarding MS Edge. Seems like it does not like the promises, so I get this: 'Unhandled promise rejection SourceUnavailableError'. Do you know if is it possible to enable this?
BTW: Really awsome plugin!

**Comment by gruhn** [comment]
Thanks :grin: 

Do you have by any chance opened another application which is already accessing your camera. For example another browser viewing the same page?

Otherwise, make sure you're on the latest version of `vue-qrcode-reader` and also check if you have the same problem on the [demo page](https://gruhn.github.io/vue-qrcode-reader/).

**Comment by alansaldivar87** [comment]
Yes I have tried the DEMO version with no luck, even with the Experimental Javascript flag enabled. There is also another issue that I have found, on production sites you get this if you are not running on a secure environment (but I think that's a good thing):
> [Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by gruhn** [comment]
Hmm... I can't reproduce this issue in Edge 40. Which version are you using?

Is the second issue you mentioned just a general hint or did you encounter this while using `vue-qrcode-reader`? I'm confused because the demo page is always served over HTTPS. In the README I also described an exception handling strategy (see `inti` event) which I expected to cover this issue.

**Comment by gruhn** [comment]
So? Could you resolve your issue?
