### ISSUE TITLE
Ability to hide video stream

### ISSUE THREAD

**Issue by gafk** [gruhn/vue-qrcode-reader#107]
Hello everyone.
Is there an opportunity not to show QrcodeStream video stream saving the ability to scan. 
I develop an augmented reality app using AR.js and the problem is that I've already has a main video stream.
I tried `display:none;` on `<video>` but after that the scanner stops working.
Also tried to make `<video>` `1px*1px` but after that the scanner stops working (or working really bad) as well.

Does anybody know how to solve my problem?

**Comment by gruhn** [comment]
Try to avoid styling the DOM elements _inside_ the component.

You could:
* wrap the component in a div and make it `visibility: hidden;`
* make the entire content of your page overlay the component using `z-index`
* position the component outside the viewport, somewhat like this:
```css
.wrapper-for-qrcode-stream {
  position: absolute;
  top: 0px;
  left: -100000px;
}
```

---------
Note that some browsers will prevent you from requesting multiple camera streams at once (Firefox maybe, I don't remember 🤔 ). Your application might be affected by this, since you say, you already have a stream running.

**Comment by gafk** [comment]
@gruhn thank you.
`visibility: hidden;` works fine.
