### ISSUE TITLE
[Feature Request] Option to Override mediastream constrains.

### ISSUE THREAD

**Issue by rajagopalx** [gruhn/vue-qrcode-reader#112]
It would be nice if there is an option to turn on / off mobile torch light.

**Comment by rajagopalx** [comment]
I refered,

https://stackoverflow.com/questions/37848494/is-it-possible-to-control-the-camera-light-on-a-phone-via-a-website/47153547#47153547

https://developers.google.com/web/updates/2016/12/imagecapture

Looks like there is torch option. But I don't know how to access the camera stream from my component.

**Comment by gruhn** [comment]
No, there is no way to get the `MediaStream` object at the moment.

One option would be to expose it via the `init` event as the payload of the given `Promise`.

We should be careful though. The `MediaStream` API is complex and continuously evolving. Once this is publicly exposed, users can read from/write to/call functions on it as they please. Allowing this is risky and work intensive since a lot of additional error cases need to be covered in the components implementation.

With restricted access, for example with a new component prop, we could of course allow torch control too. This however introduces additional complexity to the components API. I really want to avoid [feature creep](https://en.m.wikipedia.org/wiki/Feature_creep). Torch control seems to me like a very specific edge case. Especially because it's only supported in Chrome yet.

**Comment by rajagopalx** [comment]
Thanks for ur reply. Actually, we do scanning in low light conditions. (For ex, Closed Warehouse).  

Can u pls provide any props to apply constraints to media stream?

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/applyConstraints

So that we can pass our own constraints.
