### ISSUE TITLE
QrcodeCapture + detect == null

### ISSUE THREAD

**Issue by alexandernst** [gruhn/vue-qrcode-reader#119]
I'm playing with QrcodeCapture on an iOS device (iPhone 6s on iOS 12.3). I'm having a problem with reading QR codes. I subscribed to the `detect` event, and the promise is resolved correctly, but the value of `content` is `null`.

What could be the problem?

**Comment by alexandernst** [comment]
Also, after quite some tests I discovered that the closer the QR is to the camera, the more chances the `content` will get `null`ed. 

Is there any bugs that might be related to the size of the QR in the photo? I mean, if the QRs surface is more than, say, 90% of the photo, the code won't properly detect it as a QR code?

**Comment by alexandernst** [comment]
Maybe https://github.com/gruhn/vue-qrcode-reader/issues/2 ?

**Comment by gruhn** [comment]
This is intentional. 

No content is not interpreted as an error so the promise resolves correctly. If an image does not contain a QR code or the image could not be decoded then there is _no content_, hence `content == null`. 

This allows you to respond properly. If users pass some random image of the New York skyline or whatever, you can null-check for the content field and display a message like "No QR code detected, please try again".

Detection accuracy itself depends on your device, browser, the image itself and _jsQR_ (the library we use to process images). So improvement here is pretty much beyond what we can do.

**Comment by alexandernst** [comment]
I didn't explain myself correctly, sorry for that. What I ment to say is that if I take a photo of a QR, but the QR occupies too much of the photo (that is, the camera was too close to the QR), this library won't detect the QR properly. 

If I take the photo of the same QR from some distance, the library reads the QR fine.

In both cases the promise is resolved with "OK", but in the first case the content is null, despite my photo having a perfectly valid QR.

**Comment by gruhn** [comment]
The promise always resolves with "OK" whether or not the image could be decoded. So it's fine that content is null although the promise resolved. The promise only rejects in real error cases where people uploaded a PDF or something.

It's possible that you take a photo of (what looks like) a valid QR code but you get `content == null` anyway. But dealing with this issue is out of our reach. That's what I meant with _detection accuracy_.
