### ISSUE TITLE
Chrome OverconstrainedError

### ISSUE THREAD

**Issue by danivalls** [gruhn/vue-qrcode-reader#130]
Hello guys! 

I'm using QrCodeStream on my web app, but I'm facing a weird problem.
On chrome mobile works perfect, but when trying to use it on chrome desktop I get the error "OverconstrainedError". 

```javascript
OverconstrainedError {
  name: "OverconstrainedError",
  message: null,
  constraint: "facingMode"
}
```

The weird thing is that if I open the Chrome DevTools, hit on 'Toggle Device Toolbar', select any device (except 'responsive') and refresh the page, then it suddenly works! Once it starts working I can close the devTools and it keeps working perfectly.

Any idea what could be causing this weird issue? 

Thanks a lot for your help!

**Comment by gruhn** [comment]
What do pass via `camera` prop?

**Comment by danivalls** [comment]
originally I pass `rear`, and if the user clicks on a button to switch camera, the prop changes to `front`.

**Comment by gruhn** [comment]
`rear` and `front` force the browser to use the rear or front camera. If it doesn't exist on a device, the error mentioned by you is exactly what you get. 

Maybe Chrome interprets your camera differently when it tries to emulate mobile devices. Although, I never heard of something like this before and I also can't reproduce it. 

Anyway, can you try to switch between `auto` and `front` instead of `rear` and `front`.

**Comment by danivalls** [comment]
Awesome! setting the camera prop to `auto` fixed the problem. Thanks a lot!
