### ISSUE TITLE
IOS and Android(old version) phone, UNKNOWN ERROR: undefined is not a function

### ISSUE THREAD

**Issue by skyshirt** [gruhn/vue-qrcode-reader#16]
![image](https://user-images.githubusercontent.com/18375810/35312225-6cddfddc-00f5-11e8-94f4-dc1d806d424e.png)
![image](https://user-images.githubusercontent.com/18375810/35312408-37f134bc-00f6-11e8-8241-d9a8f66d7839.png)

**Comment by gruhn** [comment]
Hey, thanks for reporting. Can you tell me which iOS version you're running. For your Android phone too including browser and browser version please.

**Comment by skyshirt** [comment]
ios iphone 6 10.x and iphone 6s 11.2.5
android 5.1.1  
Mozilla/5.0 (Linux; Android 5.1.1;NX510J Build/LMY47V) AppleWebkit/537.36(KHTML,like Gecko)Version/4.0 Chrome/42.0.2311.154 Mobile Safari/537.36)

**Comment by skyshirt** [comment]
but when i use Chrome(62.0.3202.84) in android 5.1.1, it will be ok

**Comment by gruhn** [comment]
Do you always get that exact error message? This component generally doesn't work on iOS 10 and below (see #17) but I expected another error message :thinking:

Can you show me the code line where the error occurs? I know the code is minified but if you [turn on pretty print in the dev tools](http://blittle.github.io/chrome-dev-tools/sources/pretty-print.gif) I hopefully can tell where is comes from.

**Comment by skyshirt** [comment]
![image](https://user-images.githubusercontent.com/18375810/35426142-c2b3ee4a-029b-11e8-8345-acc72a705cb1.png)

**Comment by gruhn** [comment]
Thanks! The error is caught in the Promise callback. That's why you can handle it there. I need to know though where the error occurs inside the `vue-qrcode-reader` component. Sorry, I need you to find out where this error comes from. I can't reproduce it :S

 * go to the demo page
 * open the file I highlighted in the picture below
 * pretty print that file
 * find the `startCamera` function (this error must occur somewhere here)
 * set a debug breakpoint
 * reload the page
 * try to find the code line, where this TypeError comes from

![bildschirmfoto vom 2018-01-26 12-23-00](https://user-images.githubusercontent.com/26570572/35437880-b0a8c0d8-0294-11e8-9711-65f002b4f5b6.png)

**Comment by skyshirt** [comment]
yes, I know. but it's a pity that it's the same mistake
![image](https://user-images.githubusercontent.com/18375810/35470770-8c2f3efc-038a-11e8-8f9d-2f30afca8c1f.png)

**Comment by gruhn** [comment]
Weird :worried: can you check if you have similar issues [with this demo](https://schmich.github.io/instascan/)

**Comment by skyshirt** [comment]
This demo shows everything normal, without any mistakes

**Comment by gruhn** [comment]
I'm starting to think that too. I have no idea where to look though. I could try to upgrade everything Babel related and hope for the best

**Comment by gruhn** [comment]
Ok I did that, check the demo page again :pray:

**Comment by skyshirt** [comment]
![image](https://user-images.githubusercontent.com/18375810/35489984-1bc6a756-04d7-11e8-8cc8-06148a39a171.png)
This error still exists

**Comment by gruhn** [comment]
hmmm... based on your previous screenshot I assumed the error occurred in "Line 1, Column 96626" but this looks different now. Your Chrome Dev Tools look a little bit outdated. Is there really no option to [pretty print that file](http://blittle.github.io/chrome-dev-tools/sources/pretty-print.gif) so I can tell where exactly this error comes from. I'm poking around in the dark here without any further details.

**Comment by skyshirt** [comment]
It must not be the problem of developing tools
I used it to debug Android 7 and it's normal.

**Comment by gruhn** [comment]
Ok, I just saw part of the error log in your latest screenshot states that the error occurs in column *147514*. Based on that I found a piece of code that (I believe) belongs to [webrtc-adapter](https://github.com/webrtc/adapter):

![bildschirmfoto vom 2018-01-29 04-32-31](https://user-images.githubusercontent.com/26570572/35492996-6e174348-04b0-11e8-974a-153a10104d1f.png)

`find` seems to be the function that is undefined here. I assume this is the same as [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) which is confusing though because 3 code lines above, `filter` is not throwing an error although `find` is a much older array function.

Anyway, I upgraded `webrtc-adapter` so **you can check the demo page once again**. I'm not confident though, that this solved the problem. In case this is indeed a webrtc-adapte bug, I'd like to forward this issue to their repository. So can you please tell me again, which browser and browser version you are using on your *Android 5.1.1* device ? **I don't need the full user-agent string**, I don't know how to read those properly. Just tell me if it's *Chrome 42* or *Firefox 25* or something.

**Comment by skyshirt** [comment]
it's Chrome 42 nad Chrome 37

**Comment by skyshirt** [comment]
![image](https://user-images.githubusercontent.com/18375810/35495453-ee7e5918-04fb-11e8-875d-1565a747083f.png)
It's another find

**Comment by gruhn** [comment]
Ok, I believe we're on to something. I was also wrong `filter` has been longer part of the official JS than `find`.

**Comment by skyshirt** [comment]
All right. Understand what you mean, and thank you for your serious help.
This problem has been restored in the actual production environment.
Temporarily by testing whether to support Array.prototype.find to solve the problem.
