### ISSUE TITLE
System requirements?

### ISSUE THREAD

**Issue by artem0071** [gruhn/vue-qrcode-reader#17]
I'm tried to use this component but it doesn't work on my iPhone 5 v.10.3.2

What is system requirements for this component?

There is error from your site:
![jxzoqmblq6y](https://user-images.githubusercontent.com/21971875/35334540-d8e65f0a-0123-11e8-9d9f-19894c7af0c7.jpg)

This error in Safari and Chrome(newest)

**Comment by gruhn** [comment]
Short answer: it only works on **iOS 11** :disappointed: 

The error message tells you that [WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) is not supported. This is a relatively new Web API and the one we need to access a users camera from the browser. Apple first implemented it in Safari for iOS 11. Apple forces all browsers on iOS to use Safaris WebView component and doesn't allow them to implement their own. That's why, it doesn't work with Chrome either (and it won't with Firefox and so on).

The only alternative to WebRTC would be an implementation with Adobe Flash but since Apple never supported that either, there is no chance to have this component working on iPhone with iOS 10 and below.
