### ISSUE TITLE
Component mounting taking "a long time", and my proposal to improve mount time

### ISSUE THREAD

**Issue by JuhQ** [gruhn/vue-qrcode-reader#202]
I was wondering why the component takes a long time to mount, I guess I pinpointed the issue to the 500ms timeout found in  https://github.com/gruhn/vue-qrcode-reader/blob/94b663126954745d648afa61c3ccd2683265fad1/src/misc/camera.js#L111-L114

The comments in the implementation say that there's no event it could listen to, but couldn't it be possible to poll the capabilities in an interval, to see when there's an object with data in it and then continuing execution. Instead of just always waiting 500ms, even if the values are available within first milliseconds..

Something like this:

```js
await new Promise((resolve) => {
  setInterval(() => {
    const [track] = stream.getVideoTracks();
    const capabilities = track.getCapabilities();
    if (Object.keys(capabilities).length) {
      resolve(true);
    }

    // possibly check here as a fallback that interval doesn't run longer than 500ms
  }, 10);
});
```

This would for sure run more code in the process, but if it reduces mount time, it could be worth it. I'm not sure how this would effect battery life for example.

Also, it would be cool to know which devices are affected by the issue, instead of just seeing a comment of `some devices`.

**Comment by gruhn** [comment]
A little bit more context: 

The whole waiting-for-capabilities stuff was introduced together with [the torch feature](https://gruhn.github.io/vue-qrcode-reader/demos/Torch.html). Since support for that is inconsistent across devices, users needed a way to feature-detect. 

As described in the comment, on some devices the capabilities object is only initialized with significant delay after requesting the camera (calling `getUserMedia`). I can recall at least one user confirmed that this behavior occurs in Chrome on Samsung Galaxy S7.

Initially I assumed only `getCapabilities` is affected by this so stuff was executed in this order:

* activate torch (when requested)
* timeout for 500ms
* `getCapabilities`

But the torch wouldn't actually turn on the affected devices. As it turns out the whole torch feature is requires this weird delay to become available. That's why stuff is now execute in this order:

* timeout for 500ms
* `getCapabilities`
* activate torch

which seemed to have solved the problem.

On most devices this wasn't an issue either way. So I guess with polling+timeout we can safely eliminate those 500ms for most devices. However, I think you will be disappointed how little impact this has. There is always some highly visible mounting delay anyway.

**Comment by gruhn** [comment]
FYI: timeout was introduced in v2.3.3 so you might want to checkout v2.3.2 for comparison.
