### ISSUE TITLE
how do i reinit component?

### ISSUE THREAD

**Issue by denmasyarikin** [gruhn/vue-qrcode-reader#21]
i use this component inside vuetify v-dialog, in the first open, scanner is working perfectly, but for next operation mostly method onDecode never called (camera played no problem),  i think the component should be init when dialog open (in my case), so there any way to do that (reinit)?

**Comment by denmasyarikin** [comment]
sorry for this report, i finally found the answer, because the first decoded i pause the camera, on dialog open the camera its actually reinited, the problem is camera still paused on next operation. so i just set pause to false again on dialog close.

**Comment by gruhn** [comment]
I'm not sure how much you already know and since you already seem to have solved your problem, I'll just explain what's going on under the hood:

I'm not sure about vuetify. I have never used it but you should know that `vue-qrcode-reader` emits `init` as soon as it's mounted. Because showing and hiding your dialog seems not to trigger `init` again, I guess vuetify is using `v-show` for that under the hood. This does not destroy the component and therefore the component is not mounted again when you show it.

`vue-qrcode-reader` stores the most recent decoded result. We check if newly decoded values are the same as the most recent one. In case this is true, the `decode` event is not emitted again. Otherwise you might receive 6 `decode` events in a row, all with the same value. This is because in the process many frames are scanned in a short time.

This however prevents you from scanning QR codes twice even when you want to. The components inner state is lost when you destroy it so you could make sure `vue-qrcode-reader` in your dialog is destroyed every time you caught a result. Maybe using `v-if`. This triggers the hole initialization process again though, i.e. requesting user for access permission and so on. 

A better way is to use the `pause` prop. By pausing and unpausing the component, you also reset the inner representation of the most recent decoded QR code. Any subsequent decoded value will be propagated again.

I hope this was helpful. Close this issue if you don't need any further help.
