### ISSUE TITLE
QR does not read on iPhone SE. iOS 14.4

### ISSUE THREAD

**Issue by woottonn** [gruhn/vue-qrcode-reader#234]
iOS 14.4.
iPhone SE.
Using Safari.
QR does not get read, you see the red box as if it is attempting to read the code, but it doesn't. Works fine with other browsers installed on the phone.

Issue is reproducible with the demo. (https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html)

 - Device: iPhone SE
 - OS: 14.4
 - Browser Safari 14

**Comment by gruhn** [comment]
Can't reproduce. If you see the red box, the QR code was successfully detected. Could it be that the QR code you tried to read just encodes _empty string_ or maybe a bunch of spaces? If so try a some of these: 

https://www.google.com/search?q=qrcode&source=lnms&tbm=isch&biw=1920&bih=949

Otherwise please provide the QR code you tried to scan.

**Comment by woottonn** [comment]
Hi gruhn.

It seems that it is now working, very strange. I tried using chrome and other browsers and they worked fine on that phone. Then today, for whatever reason (without installing any updates) it is now working. Who knows! Thanks for getting back to me.
