### ISSUE TITLE
Issue with iPhone iOS

### ISSUE THREAD

**Issue by ajdinmuratovic35** [gruhn/vue-qrcode-reader#245]
Hello, I have an issue with with vue-qrcode-reader on iPhone where it does not work. Do you have a suggestion how to make it works on iOS iPhone?

**Comment by gruhn** [comment]
Check the browser support table on iOS: 

https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#browser-support

Also always check whether whatever problem you have also occurs on the demo page: 

https://gruhn.github.io/vue-qrcode-reader/demos/CustomTracking.html

In general, you have to give some more detail. Otherwise people can't help you.

**Comment by samydoesit** [comment]
We are trying to get it running with nuxt and capacitorJS.

After compiling to native ios App there is no https so you have to also install cordova-plugin-iosrtc to get WebRTC W3C JavaScript APIs working on http for ios.

I did all that but after that when i try to use vue-qr-code-reader (it's only sometimes working) i am only seeing the face/front cam. 

When i manually call navigator.mediaDevices.enumdevices() and pick the right deviceId for rear camera and call navigator.getUserMedia and attach that stream to a video element everything is working fine. Any way to provide a custom video stream to vue-qr-code-reader or pass deviceId directly?
