### ISSUE TITLE
New version(3.0.4~)QrcodeCapture will not decode something from iOS camera.(iOS15)

### ISSUE THREAD

**Issue by yknamja** [gruhn/vue-qrcode-reader#284]
Thanks for fixed the qrcode-stream problem in iOS15, 
but I don't know why this version qrcode capture can't decode something from iOS15 camera.
version 2.3.3 will be decoded, but the new version vue-qrcode-reader cant't decode the same qrcode from iOS15 device.
Thank you.

When I use detect function to check content, content will be null.
https://gruhn.github.io/vue-qrcode-reader/demos/Upload.html

<img width="331" alt="スクリーンショット 2021-11-22 午後1 17 08" src="https://user-images.githubusercontent.com/79449228/142805325-19591514-ba92-4b15-9be5-ebf27ead9ce1.png">

**Comment by yknamja** [comment]
It's the same with this problem.
https://github.com/gruhn/vue-qrcode-reader/issues/239

**Comment by arnebr** [comment]
I think it also duplicates #283

**Comment by yknamja** [comment]
> I think it also duplicates #283

But 2.3.3 version in iOS15 is decoded correctly, so I think it's not iOS version.
I tried to use another package (camera upload function) also detected correctly.

**Comment by nowackipawel** [comment]
Not sure, but in my case it is because there is no way to load some external library that is doing a job.
[Error] Failed to load resource: bad URL (jsQR.min.js, line 0)
[Error] Failed to load resource: bad URL (jsQR.min.js, line 0)

It is working nicely on android but iphone 13 pro (ios 15.x) is blocking this resource.
