### ISSUE TITLE
can't open the camera in  wechat browser ,iOS system

### ISSUE THREAD

**Issue by bububear** [gruhn/vue-qrcode-reader#375]
**Describe the bug**
Can't open the camera in  Wechat browser ,iOS system reproduce this issue with [one of the demos](https://vue-qrcode-reader.netlify.app/demos/ScanSameQrcodeMoreThanOnce.html)

**To Reproduce**
One  of the demos  : https://vue-qrcode-reader.netlify.app/demos/ScanSameQrcodeMoreThanOnce.html

**Screenshots**
![4a6a73dbb853bce91bee3f227f19255](https://github.com/gruhn/vue-qrcode-reader/assets/35417310/9f14fa08-0d55-442a-95d2-a06f40a82ed9)

**Smartphone (please complete the following information):**
 - Device: [Phone6s Plus]
 - OS: [iOS]
 - Browser [Wechat broswer]

**Comment by Sec-ant** [comment]
This looks like a WebRTC issue in WKWebView on early iOS devices: 

- https://developers.weixin.qq.com/community/develop/doc/000ca0c5f70f48f241de9b75f5b000
- https://www.jianshu.com/p/ac585a7d3241
- https://developers.weixin.qq.com/community/develop/doc/00046e23fbc93807649c34ed551400

**Comment by bububear** [comment]
On the basis of iOS 14.3 and later, the camera still cannot be turned on.

**Comment by Sec-ant** [comment]
I just remembered I have an iPhone SE 1st generation and I successfully reproduced this problem.

Upload two videos for demonstration:

https://github.com/gruhn/vue-qrcode-reader/assets/10386119/a1054054-23f9-48ae-977e-383d7bffac2d

https://github.com/gruhn/vue-qrcode-reader/assets/10386119/460b98be-b24d-493e-9015-9b8b86732593

iOS 15.5, Safari 15.5, WebKit 6613.2.7

I may do some debugging when I have time. Though it's not easy because I don't have a mac.

**Comment by Sec-ant** [comment]
Adding this line of code

```ts
videoEl.play()
```

before awaiting [`Promise.race`](https://github.com/gruhn/vue-qrcode-reader/blob/be19c8553c8b59907adf154d430a45be8b631970/src/misc/camera.ts#L85C1-L95C5) seems fixes this problem:

https://github.com/gruhn/vue-qrcode-reader/assets/10386119/b56a5454-50d0-47eb-a743-bd5b594de248
