### ISSUE TITLE
When changing torch status it stop detecting codes

### ISSUE THREAD

**Issue by gkucmierz** [gruhn/vue-qrcode-reader#394]
**Describe the bug**
When changing torch status it stop detecting qr codes.

**To Reproduce**
change torch status

**Screenshots**
![Screenshot_20231120-113908](https://github.com/gruhn/vue-qrcode-reader/assets/739084/707fdab6-2c61-46b1-a2ba-435373188a7f)

**Smartphone (please complete the following information):**
 - Device: pixel
 - Browser chrome

**Comment by gkucmierz** [comment]
Actually it stops tracking and detecting codes immediately after something on DOM is changed.

**Comment by nitsir** [comment]
+1 same issue 
In some cases can be fixed by toggling prop "paused", but not in all cases

**Comment by gkucmierz** [comment]
> +1 same issue In some cases can be fixed by toggling prop "paused", but not in all cases

I noticed this too, but pausing & unpausing introduces unnecessary delay.

**Comment by gkucmierz** [comment]
https://inspiring-hotteok-8764c2.netlify.app
https://github.com/gkucmierz/qr-code

**Comment by Sec-ant** [comment]
@gkucmierz for your case, I think the reason is that you're passing `constraints` an object literal, which will cause component to re-render each time the template runs. You can use `v-memo` or composite the constraints object in the script and reference it at the props instead.

Nevertheless, re-rendering shouldn't break the component, so there might be something need to change on the `vue-qrcode-reader` side.

I have zero dev experience with Vue, let's hope someone else can take a closer look into this.

**Comment by gkucmierz** [comment]
@Sec-ant it helped
https://github.com/gkucmierz/qr-code/commit/78c580f0f8e62b5017020b89d39eb5dc6ac0be08

But outline still freezes when torch status is changed.
