### ISSUE TITLE
camera does not appear / not showing when i deploy the application in server

### ISSUE THREAD

**Issue by apeengggg** [gruhn/vue-qrcode-reader#398]
I have tried locally and successfully displayed the camera and read QR, when I deploy to the server, the camera does not appear, how do I solve it? I don't use https

**Comment by apeengggg** [comment]
iam using vuejs3, with core ui template

**Comment by Sec-ant** [comment]
You can only use the camera in a secure context (https or localhost): https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by apeengggg** [comment]
> You can only use the camera in a secure context (https or localhost): https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

so how to allow it in http ?

**Comment by Sec-ant** [comment]
The detection of insecure context is hardcoded here: https://github.com/gruhn/vue-qrcode-reader/blob/504e46d2d01c70fce4679740294849b12e18f325/src/misc/camera.ts#L32-L40

So `chrome://flags/#unsafely-treat-insecure-origin-as-secure` is not gonna work.

Do you have a reason to serve this in an insecure context?

**Comment by apeengggg** [comment]
> The detection of insecure context is hardcoded here:
> 
> https://github.com/gruhn/vue-qrcode-reader/blob/504e46d2d01c70fce4679740294849b12e18f325/src/misc/camera.ts#L32-L40
> 
> So `chrome://flags/#unsafely-treat-insecure-origin-as-secure` is not gonna work.
> 
> Do you have a reason to serve this in an insecure context?

i dont have spesific reason to serve that in an insecure origin, what should i check ?

**Comment by Sec-ant** [comment]
> i dont have spesific reason to serve that in an insecure origin, what should i check ?

Sorry I don't understand your question. I was asking your use case?

- If you're deploying the service to end users, you'll need an SSL certificate because it's [very unsafe to `getUserMedia` in a insecure context](https://stackoverflow.com/a/34198101).

- For local development and testing, `localhost` is required, or check the [README](https://github.com/gruhn/vue-qrcode-reader?tab=readme-ov-file#im-running-a-dev-server-on-localhost-how-to-test-on-my-mobile-device-without-https) to learn how to test your service on your mobile device without https.

- If you really want `chrome://flags/#unsafely-treat-insecure-origin-as-secure` to work. You can fork or patch the `vue-qrcode-reader` to comment out this piece of detection code: https://github.com/gruhn/vue-qrcode-reader/blob/504e46d2d01c70fce4679740294849b12e18f325/src/misc/camera.ts#L32-L40 And set your insecure origin in the chrome flags page.
