### ISSUE TITLE
structured-clone is not defined

### ISSUE THREAD

**Issue by ketao4869** [gruhn/vue-qrcode-reader#401]
https://ask.dcloud.net.cn/question/147298

https://github.com/search?q=repo%3Agruhn%2Fvue-qrcode-reader+structured-clone&type=code

**Comment by ketao4869** [comment]
The reason is that the browser environment is too old and there is no structured-clone API yet.

I see structured-clone in the dependency package, but I don’t know where to use it.

**Comment by ketao4869** [comment]
![image](https://github.com/gruhn/vue-qrcode-reader/assets/54937496/31ab028b-92af-48fc-80b9-ea82b170c643)

**Comment by Sec-ant** [comment]
Ah, another issue caused by my careless introduction of new features🤦.

This problem lies in the the dependency `zxing-wasm`.

`structuredClone` is used here:
https://github.com/Sec-ant/zxing-wasm/blob/9fcd626d57cd48b1b60c5fd095ef3b61f695b257/src/bindings/exposedReaderBindings.ts#L2
and here:
https://github.com/Sec-ant/zxing-wasm/blob/9fcd626d57cd48b1b60c5fd095ef3b61f695b257/src/bindings/exposedWriterBindings.ts#L2

The reason is that I want to expose the default options (for users to play with) while in the meantime I do not want it to be mutated.

Good news is that it doesn't affect the core function of the package. So a simple workaround would be polyfilling a dummy `structuredClone` function in the global before you importing this package:

```ts
globalThis.structuredClone = _ => _;
import { QrcodeStream } from "vue-qrcode-reader";
...
```

I'll push a fix to remove the using of `structuredClone` shortly after.

Thanks for bring this issue up.
