### ISSUE TITLE
QR scan area overflowing in Safari on iOS

### ISSUE THREAD

**Issue by dakshshah96** [gruhn/vue-qrcode-reader#62]
I've implemented the QR code reader in my Vue app and it looks as expected when I check it with Chrome Developer Tools mobile view (iPhone 6/7/8).

![screenshot 2018-09-09 15 04 09](https://user-images.githubusercontent.com/7896438/45263153-c83b3f00-b441-11e8-9ace-db279bf04cde.png)

However, this is not replicated when I open the web app on my iPhone using Safari. The camera view overflows the rectangular box with white border:

![photo-2018-09-09-15-06-25](https://user-images.githubusercontent.com/7896438/45263219-f0776d80-b442-11e8-8233-5af4a8ca9202.jpg)

The code for my scan page is:

```
<template>
  <div class="scan-content">
    <div class="scan-ready">
      <div class="title">Scan the QR code</div>
      <qrcode-reader @decode="onDecode" :paused="qrPaused"></qrcode-reader>
      <md-button class="md-raised" @click="cancelScan">Cancel</md-button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'QrScan',
  data: () => ({
    progressBar: false,
    decodedString: 'nothing received yet',
    qrPaused: false
  }),
  methods: {
    onDecode (decodedString) {
      this.decodedString = decodedString
      this.qrPaused = true
      alert(decodedString)
    },
    cancelScan () {
      this.$router.replace('/app')
    }
  }
}
</script>

<style scoped>
.scan-content {
  height: 100%;
  background-color: lightgrey;
}

.scan-loader svg {
  width: 50px;
  height: 50px;
}

.scan-ready {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  height: 100%;
}

.scan-ready {
  text-align: center;
  font-size: 20px;
}

.scan-ready .title {
  padding: 20px 50px;
  text-align: center;
  font-size: 18px;
  background-color: white;
}
.qrcode-reader {
  max-width: 400px;
  margin: 20px 15px;
  border: 5px solid white;
}
</style>
```

**Comment by gruhn** [comment]
Unfortunately I have no way to test on iOS so you have to figure out why this is happening. Which element is causing the overflow? Can you come up with minimal CSS modifications that fix this?

In general, try not to override internally used CSS classes. Use a wrapper element instead to constrain the size of the component. 

```html
<div class="wrapper">
  <qrcode-reader></qrcode-reader>
</div>
```
```css
.wrapper {
  max-width: 400px;
  margin: 20px 15px;
  border: 5px solid white;
}
```

P.S.: that's a nice clean UI you have there. Is that some kind of Material Design library?

**Comment by dakshshah96** [comment]
@gruhn Glad you liked the UI! I'm using [Vue Material](http://vuematerial.io). 😄 

I tried what you suggested, now the camera content is inside the white border but the wrapper itself is extended:

![img_5120](https://user-images.githubusercontent.com/7896438/45265160-adc68d00-b464-11e8-9900-1e669e533032.PNG)

Any ideas?

**Comment by gruhn** [comment]
The height of the qrcode-reader component is determined by the cameras resolution. In your case it shares the available space in .scan-ready with two other elements. Since the container is a flex column the child elements should be nicely distributed unless the container is limited to a specific height.

So my best guess is: You have a wrapper element outside of your component with a fixed height. Both .scan-ready and .scan-content inherit that height due to height: 100% . On Desktop you have a different camera installed with relatively smaller vertical resolution. So in Chrome it still fits but on iOS the elements start to overlap.

If that's the case you might want to remove that fixed height.

**Comment by dakshshah96** [comment]
@gruhn Ah, that makes sense! 

Is there any way to restrict the height of the qrcode-reader component instead of determining it by the cameras resolution? I just want a small rectangular scanning area.

**Comment by gruhn** [comment]
Well, you could make the wrappers width even smaller. The aspect ratio is preserved so that will also reduce the height. That might not be so visually appealing though and it's hard implement this dynamically for

**Comment by gruhn** [comment]
Well, you could make the wrappers width even smaller. The aspect ratio is preserved so also the height is reduced. That might be not so visually appealing though and it's hard to implement so that it works dynamically with different screen sizes.

If you just want to avoid a scroll bar and ensure that the hole content of that view fits you can also consider to let some elements overlay the camera stream. You can easily achieve that like this:

```html
<qrcode-reader>
   overlay elements here!
</qrcode-reader> 
```

Another solution I can think of is to crop the additional height. You can achieve that with two wrapper elements for the qrcode-reader component. An outer wrapper that takes up the height available. Not more not less. Any overflow is hidden. The inner wrapper makes sure that the component is centered and not only the lower end is cropped. [Checkout this fiddle](https://jsfiddle.net/0723g5kn/20/). Problem with this solution is that the hidden areas are still scanned for QR codes. So even half visible QR codes are matched. Users might find that confusing.

**Comment by dakshshah96** [comment]
Thank you so much for the detailed help @gruhn! 🎉 

I ended up reducing the width of my wrapper finally to get a decent result on all major phones.

**Comment by hcly3015** [comment]
In mobile Safari is OK. but in other mobile browser do not run. that is why??
