### ISSUE TITLE
Dragover event not emited for dropzone

### ISSUE THREAD

**Issue by mix359** [gruhn/vue-qrcode-reader#97]
Hi,

I'm implementing this library and I'm finding some problems with the dropzone component.
In the example in the documentation there's a onDragOver callback function that should change the of a variable to track if a user is dropping something on the component, but this callback is never called, even in the demo example.
I've tested it with Firefox and Chrome on a MacOs but if it's needed I can check with other browser.

Looking at the code in the QrcodeDropZone component I can see a @dragover.prevent.stop event catcher. Maybe this one is preventing it from passing the event up in the chain.
I can do some test if this can help solve the problem, and eventually send a PR?

Thanks
Cheers Mix

**Comment by gruhn** [comment]
Thanks for reporting this. I just haven't implemented the `dragover` event as it's presented in the demo yet. I must have accidentally updated the demo prematurely. 

What you found in the code is referring to the native DOM event also called `dragover`.

Because this naming collision might cause some confusion I was hesitating to publish the new feature. This won't prevent users from listening to the native DOM event though. You can leverage the [Vues native event modifier](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components). So this is just a matter of convenience.

I can't think of a different name for this event that is as short and yet as expressive as `dragover`. This is really important in my opinion and since I don't believe there is really a reason to prefer the native DOM event over the custom event, I think it makes sense to go with name anyway.

Unless you have any objections, I'll publish a new release soon.

**Comment by mix359** [comment]
Thanks for the reply and the clarification.
Effectively looking at the code I was thinking that you were using the DOM event dragover, and I can understand the problem.

I don't understand why you need to emit a fake dragover event, when the DOM is already providing one? 
To make it simpler to implement the graphical change? (passing a simple boolean that report if the element is in the area or not as an argument?)
In case, i think something like "draggingover" could be used as the name of the event to not overlap the original one.

In case could be useful don't stopping the propagation of the original DOM event, if someone would attach to it, to make for example an advanced effect the use more data from the event, like the mouse position.

Thanks for your work ;)
Cheers Mix

**Comment by gruhn** [comment]
> I don't understand why you need to emit a fake dragover event, when the DOM is already providing one?
To make it simpler to implement the graphical change? (passing a simple boolean that report if the element is in the area or not as an argument?)

Exactly. Native `dragover` fires periodically every few hundred milliseconds as long as the user is actually dragging over. With Vues reactivity, this is unnecessarily awkward. 

> something like "draggingover" could be used as the name of the event

I had that one in mind too, but it's already too verbose in my opinion. I feel like keeping things concise is very much part of Vues spirit. I admit this is a rather subjective argument though.

 > In case could be useful don't stopping the propagation of the original DOM event, if someone would attach to it, to make for example an advanced effect the use more data from the event, like the mouse position.

Only parent elements are affected by this. You can still bind listeners to child elements and even pre filter events like so:

```html
<qrcode-drop-zone>
  <div @dragover="handle">...</div>
</qrcode-drop-zone>
```
```js
methods: {
  handle (event) {
    // to prevent QrcodeDropZone from
    // processing the event, call
    event.stopPropagation()
  }
}

**Comment by gruhn** [comment]
Added in v1.4.0
